import { snapLengthToGrid } from "./tacticalGrid.ts";
import type { CrowdSurgePreset, EncounterPhase, FamilyMutation, InitiativeEntry, PhaseMutation, Point, TacticalAoe, TacticalFamily, TacticalState, TacticalTether, TacticalToken, ThresholdRule } from "../types/tactical";
import { normalizePolygonArea, polygonArea } from "./tacticalPolygons.ts";

export const MIN_POLYGON_VERTICES = 3;
export const distance = (a: Point, b: Point) => Math.hypot(b.x-a.x,b.y-a.y);
export const translatePoints = (points: Point[], d: Point) => points.map(p=>({x:p.x+d.x,y:p.y+d.y}));
export const pointsEqual=(a:Point[],b:Point[],tolerance=1e-6)=>a.length===b.length&&a.every((p,i)=>Math.abs(p.x-b[i].x)<=tolerance&&Math.abs(p.y-b[i].y)<=tolerance);
export function ensureCrowdOriginals(state:TacticalState){let changed=false;state.crowdRegions.forEach(crowd=>{if(!crowd.originalPoints){crowd.originalPoints=structuredClone(crowd.points);changed=true}});return changed}
export function returnCrowdToOriginal(state:TacticalState,crowdId:string){const crowd=state.crowdRegions.find(c=>c.id===crowdId);if(!crowd)throw new Error("Crowd not found");crowd.originalPoints??=structuredClone(crowd.points);crowd.points=structuredClone(crowd.originalPoints);crowd.state="idle";state.eventLog.push({id:crypto.randomUUID(),label:`${crowd.name} returned to original configuration`,at:new Date().toISOString()});return state}
export function setCrowdOriginal(state:TacticalState,crowdId:string){const crowd=state.crowdRegions.find(c=>c.id===crowdId);if(!crowd)throw new Error("Crowd not found");crowd.originalPoints=structuredClone(crowd.points);return state}
export const moveVertex = (points: Point[], index: number, point: Point) => points.map((p,i)=>i===index?point:p);
export function insertVertex(points:Point[], edge:number, point?:Point){if(!points.length)return points;const a=points[edge],b=points[(edge+1)%points.length],p=point??{x:(a.x+b.x)/2,y:(a.y+b.y)/2};return [...points.slice(0,edge+1),p,...points.slice(edge+1)]}
export const removeVertex=(points:Point[],index:number)=>points.length<=MIN_POLYGON_VERTICES?points:points.filter((_,i)=>i!==index);
const rotate=(p:Point,degrees:number)=>{const r=degrees*Math.PI/180;return{x:p.x*Math.cos(r)-p.y*Math.sin(r),y:p.x*Math.sin(r)+p.y*Math.cos(r)}};
export function resizeAoe(a:TacticalAoe,p:Point,battlefield?:TacticalState["battlefield"]){const d={x:p.x-a.x,y:p.y-a.y},local=rotate(d,-(a.rotation??0));const snap=(value:number)=>a.snapToGrid!==false&&battlefield?snapLengthToGrid(value,battlefield):Math.max(5,value);if(a.shape==="line")return{...a,size:snap(local.x),width:snap(Math.abs(local.y)*2)};if(a.shape==="square"){const size=snap(Math.max(Math.abs(local.x),Math.abs(local.y))*2);return{...a,size,width:size}}if(a.shape==="rectangle")return{...a,size:snap(Math.abs(local.x)*2),width:snap(Math.abs(local.y)*2)};return{...a,size:snap(Math.hypot(d.x,d.y))}}
export const rotateAoe=(a:TacticalAoe,p:Point)=>({...a,rotation:Math.atan2(p.y-a.y,p.x-a.x)*180/Math.PI});
export const waypointDistance=(points:Point[],grid:number,units:number)=>points.slice(1).reduce((sum,p,i)=>sum+distance(points[i],p),0)/grid*units;
export function objectsInRect(s:TacticalState,a:Point,b:Point){const x1=Math.min(a.x,b.x),x2=Math.max(a.x,b.x),y1=Math.min(a.y,b.y),y2=Math.max(a.y,b.y),inside=(p:Point)=>p.x>=x1&&p.x<=x2&&p.y>=y1&&p.y<=y2;return [...s.tokens.filter(t=>t.visible&&t.x+t.size/2>=x1&&t.x-t.size/2<=x2&&t.y+t.size/2>=y1&&t.y-t.size/2<=y2).map(x=>x.id),...s.aoes.filter(inside).map(x=>x.id),...s.spotlights.filter(inside).map(x=>x.id),...s.annotations.filter(inside).map(x=>x.id),...s.zones.filter(z=>z.points.some(inside)).map(x=>x.id),...s.crowdRegions.filter(z=>z.points.some(inside)).map(x=>x.id)]}
export function detectStacks(points:Array<Point&{id:string}>,tolerance:number){const remaining=new Set(points.map(x=>x.id)),result:string[][]=[];for(const p of points){if(!remaining.has(p.id))continue;const group=points.filter(o=>remaining.has(o.id)&&distance(p,o)<=tolerance).map(x=>x.id);group.forEach(id=>remaining.delete(id));if(group.length>1)result.push(group)}return result}
export const fanOut=(center:Point,ids:string[],radius=45)=>Object.fromEntries(ids.map((id,i)=>[id,{x:center.x+Math.cos(i/ids.length*Math.PI*2)*radius,y:center.y+Math.sin(i/ids.length*Math.PI*2)*radius}]));
export const applyThresholdRules=(pressure:number,rules:ThresholdRule[])=>(rules??[]).filter(r=>r.enabled&&(r.comparison==="below"?pressure<r.threshold:pressure>=r.threshold)).map(r=>r.mutation);
const tacticalObjects=(s:TacticalState)=>[...s.tokens,...s.zones,...s.crowdRegions,...s.aoes,...s.spotlights,...s.annotations,...s.tethers];
export function setFamilyMembership(s:TacticalState,objectId:string,familyId?:string){const object=tacticalObjects(s).find(x=>x.id===objectId);if(!object)return s;s.families.forEach(f=>f.memberIds=f.memberIds.filter(id=>id!==objectId));object.familyId=familyId;const family=familyId&&s.families.find(f=>f.id===familyId);if(family&&!family.memberIds.includes(objectId))family.memberIds.push(objectId);return s}
export function deleteFamily(s:TacticalState,familyId:string){const family=s.families.find(f=>f.id===familyId);if(family)family.memberIds.forEach(id=>setFamilyMembership(s,id));tacticalObjects(s).filter(x=>x.familyId===familyId).forEach(x=>x.familyId=undefined);s.families=s.families.filter(f=>f.id!==familyId);return s}
export function repairFamilyMembership(s:TacticalState){s.families.forEach(f=>f.memberIds=[]);tacticalObjects(s).forEach(object=>{if(object.familyId&&s.families.some(f=>f.id===object.familyId))setFamilyMembership(s,object.id,object.familyId);else object.familyId=undefined});return s}
export function applyFamilyMutation(s:TacticalState,id:string,m:FamilyMutation){const f=s.families.find(x=>x.id===id);if(!f)return s;const patch=(items:Array<{id:string;familyId?:string;visible?:boolean;presentationVisible?:boolean;presentationLabelVisible?:boolean;locked?:boolean;active?:boolean}>)=>items.forEach(x=>{if(x.familyId!==id&&!f.memberIds.includes(x.id))return;if(m.visible!=null&&"visible"in x)x.visible=m.visible;if(m.presentationVisible!=null)x.presentationVisible=m.presentationVisible;if(m.presentationLabelVisible!=null&&"category" in x)x.presentationLabelVisible=m.presentationLabelVisible;if(m.locked!=null)x.locked=m.locked;if(m.active!=null&&"active"in x)x.active=m.active});[s.tokens,s.zones,s.crowdRegions,s.aoes,s.spotlights,s.annotations,s.tethers].forEach(x=>patch(x));if(m.active!=null)f.active=m.active;if(m.presentationVisible!=null)f.presentationVisible=m.presentationVisible;if(m.locked!=null)f.locked=m.locked;return s}
export function applyObjectMutation(s:TacticalState,id:string,m:FamilyMutation&{pressure?:number;crowdState?:TacticalState["crowdRegions"][number]["state"]}){
  const objects=[...s.tokens,...s.zones,...s.crowdRegions,...s.aoes,...s.spotlights,...s.annotations,...s.tethers];
  const object=objects.find(x=>x.id===id) as (typeof objects[number]&{pressure?:number;state?:string})|undefined;
  if(!object)return s;
  if(m.visible!=null&&"visible"in object)object.visible=m.visible;
  if(m.presentationVisible!=null)object.presentationVisible=m.presentationVisible;
  if(m.presentationLabelVisible!=null){const token=s.tokens.find(x=>x.id===id);if(token)token.presentationLabelVisible=m.presentationLabelVisible;}
  if(m.locked!=null)object.locked=m.locked;
  if(m.active!=null&&"active"in object)object.active=m.active;
  if(m.pressure!=null&&"pressure"in object)object.pressure=m.pressure;
  if(m.crowdState!=null&&"state"in object)object.state=m.crowdState;
  return s;
}
export function applyPhase(s:TacticalState,p:EncounterPhase){s.activePhaseId=p.id;(p.mutations??[]).forEach(m=>m.targetType==="family"?applyFamilyMutation(s,m.targetId,m.changes):applyObjectMutation(s,m.targetId,m.changes));s.tokens.forEach(t=>{if(p.activeTokenIds?.includes(t.id))t.visible=true;if(p.showPresentationTokenIds?.includes(t.id))t.presentationVisible=true;if(p.hidePresentationTokenIds?.includes(t.id))t.presentationVisible=false});s.zones.forEach(z=>{if(p.activeZoneIds?.includes(z.id))z.active=true;if(p.showPresentationZoneIds?.includes(z.id))z.presentationVisible=true;if(p.hidePresentationZoneIds?.includes(z.id))z.presentationVisible=false});s.crowdRegions.forEach(c=>{if(p.activeCrowdRegionIds?.includes(c.id))c.active=true;if(p.showPresentationCrowdRegionIds?.includes(c.id))c.presentationVisible=true;if(p.hidePresentationCrowdRegionIds?.includes(c.id))c.presentationVisible=false});p.showPresentationFamilyIds?.forEach(id=>applyFamilyMutation(s,id,{presentationVisible:true}));p.hidePresentationFamilyIds?.forEach(id=>applyFamilyMutation(s,id,{presentationVisible:false}));return s}
export const familyMembers=(s:TacticalState,f:TacticalFamily)=>{const ids=new Set(f.memberIds);return[...s.tokens,...s.zones,...s.crowdRegions,...s.aoes,...s.spotlights,...s.annotations,...s.tethers].filter(x=>ids.has(x.id)||x.familyId===f.id)};
export function tacticalObjectLabel(s:TacticalState,id:string){const groups=[
  [s.tokens,"Token"],[s.zones,"Zone"],[s.crowdRegions,"Crowd"],[s.aoes,"AoE"],[s.spotlights,"Spotlight"],[s.annotations,"Annotation"],[s.tethers,"Tether"]
] as const;for(const [items,type] of groups){const item=items.find(x=>x.id===id) as {name?:string;text?:string;label?:string}|undefined;if(item){const label=item.name||item.label||item.text?.trim().slice(0,40)||type;return{label,type}}}return{label:"Unknown object",type:"Legacy"}}

export function saveCrowdSurgePreset(state:TacticalState,crowdId:string,input:{id?:string;name:string;points:Point[];createdAt?:string}){const crowd=state.crowdRegions.find(c=>c.id===crowdId);if(!crowd)throw new Error("Crowd not found");crowd.originalPoints??=structuredClone(crowd.points);const sourceArea=polygonArea(crowd.points),points=normalizePolygonArea(input.points,sourceArea),preset:CrowdSurgePreset={id:input.id??crypto.randomUUID(),name:input.name.trim()||"Untitled surge",points,createdAt:input.createdAt??new Date().toISOString(),sourceArea};crowd.surgePresets=[...(crowd.surgePresets??[]).filter(p=>p.id!==preset.id),preset];return preset}
export function triggerCrowdSurgePreset(state:TacticalState,crowdId:string,presetId:string){const crowd=state.crowdRegions.find(c=>c.id===crowdId),preset=crowd?.surgePresets?.find(p=>p.id===presetId);if(!crowd||!preset)throw new Error("Surge preset not found");crowd.originalPoints??=structuredClone(crowd.points);crowd.points=structuredClone(preset.points);crowd.state="surging";state.eventLog.push({id:crypto.randomUUID(),label:`${crowd.name} triggered surge ${preset.name}`,at:new Date().toISOString()});return state}

export type TacticalSelection = { kind:"token"|"zone"|"crowd"|"aoe"|"spotlight"|"annotation"|"tether"; id:string };
export const selectionKey=(selection:TacticalSelection)=>`${selection.kind}:${selection.id}`;
export type RulerPoint=Point&{altitude?:number};
export type TwoClickMeasurement={status:"drawing";start:RulerPoint;preview:RulerPoint}|{status:"finished";start:RulerPoint;end:RulerPoint}|null;
export function measurementClick(current:TwoClickMeasurement,point:RulerPoint):TwoClickMeasurement{return current?.status==="drawing"?{status:"finished",start:current.start,end:point}:{status:"drawing",start:point,preview:point}}
export function measurementPointerMove(current:TwoClickMeasurement,point:RulerPoint):TwoClickMeasurement{return current?.status==="drawing"?{...current,preview:{...point,altitude:point.altitude??current.preview.altitude??0}}:current}
export const objectAltitude=(value:{altitude?:number}|undefined)=>value?.altitude??0;
export const isAirborne=(value:{altitude?:number}|undefined)=>objectAltitude(value)>0;
export function rulerDistance(points:RulerPoint[],gridSize:number,distancePerSquare:number,mode:"2d"|"3d"){let horizontal=0,vertical=0,distance=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],h=Math.hypot(b.x-a.x,b.y-a.y)/gridSize*distancePerSquare,v=Math.abs(objectAltitude(b)-objectAltitude(a));horizontal+=h;vertical+=v;distance+=mode==="3d"?Math.hypot(h,v):h}return{horizontal,vertical,distance}}
export function setObjectAltitude<T extends {altitude?:number;locked?:boolean}>(object:T,value:number){if(!object.locked)object.altitude=value;return object}
export function toggleSelection(current:TacticalSelection[],next:TacticalSelection,modifier:boolean){if(!modifier)return[next];const key=selectionKey(next);return current.some(x=>selectionKey(x)===key)?current.filter(x=>selectionKey(x)!==key):[...current,next]}
export function selectionsInRect(s:TacticalState,a:Point,b:Point):TacticalSelection[]{const ids=new Set(objectsInRect(s,a,b));return[...s.tokens.map(x=>({kind:"token" as const,id:x.id})),...s.aoes.map(x=>({kind:"aoe" as const,id:x.id})),...s.spotlights.map(x=>({kind:"spotlight" as const,id:x.id})),...s.annotations.map(x=>({kind:"annotation" as const,id:x.id})),...s.zones.map(x=>({kind:"zone" as const,id:x.id})),...s.crowdRegions.map(x=>({kind:"crowd" as const,id:x.id}))].filter(x=>ids.has(x.id))}
export function moveSelections(s:TacticalState,selections:TacticalSelection[],delta:Point){const keys=new Set(selections.map(selectionKey)),move=<T extends Point&{id:string;locked?:boolean}>(kind:TacticalSelection["kind"],items:T[])=>items.forEach(x=>{if(keys.has(`${kind}:${x.id}`)&&!x.locked){x.x+=delta.x;x.y+=delta.y}});move("token",s.tokens);move("aoe",s.aoes);move("spotlight",s.spotlights);move("annotation",s.annotations);for(const [kind,items] of [["zone",s.zones],["crowd",s.crowdRegions]] as const)items.forEach(x=>{if(keys.has(`${kind}:${x.id}`)&&!x.locked)x.points=translatePoints(x.points,delta)});return s}
export type TacticalHistory={past:TacticalState[];present:TacticalState;future:TacticalState[]};
export const commitHistory=(history:TacticalHistory,next:TacticalState):TacticalHistory=>({past:[...history.past,structuredClone(history.present)],present:structuredClone(next),future:[]});
export const undoHistory=(history:TacticalHistory):TacticalHistory=>history.past.length?{past:history.past.slice(0,-1),present:structuredClone(history.past.at(-1)!),future:[structuredClone(history.present),...history.future]}:history;
export const redoHistory=(history:TacticalHistory):TacticalHistory=>history.future.length?{past:[...history.past,structuredClone(history.present)],present:structuredClone(history.future[0]),future:history.future.slice(1)}:history;
export const createCheckpoint=(state:TacticalState,label:string,id=crypto.randomUUID(),at=new Date().toISOString())=>({id,label,createdAt:at,state:structuredClone(state)});
export function meaningfulStateChange(before:TacticalState,after:TacticalState){return JSON.stringify(before)!==JSON.stringify(after)}
export async function checkpointBeforeMutation(checkpoint:()=>Promise<unknown>,mutation:()=>void){await checkpoint();mutation()}
export function createCheckpointGate(){let committed=false;return{shouldCreate:(before:TacticalState,after:TacticalState)=>!committed&&meaningfulStateChange(before,after),markCreated:()=>{committed=true}}}
export function moveTetherEndpoint(s:TacticalState,id:string,end:"from"|"to",point:Point){const tether=s.tethers.find(t=>t.id===id);if(!tether||tether.locked||tether[`${end}TokenId`]||tether[`${end}CrowdId`]||tether[`${end}ZoneId`]||tether[`${end}AoeId`])return s;tether[end]=point;return s}
export function createTether(input:{style?:TacticalTether["style"];fromTokenId?:string;toTokenId?:string;fromCrowdId?:string;toCrowdId?:string;fromZoneId?:string;toZoneId?:string;fromAoeId?:string;toAoeId?:string;from?:Point;to?:Point;category?:TacticalTether["category"];label?:string;presentationVisible?:boolean},id=crypto.randomUUID()):TacticalTether{return{id,style:input.style??"normal",fromTokenId:input.fromTokenId,toTokenId:input.toTokenId,fromCrowdId:input.fromCrowdId,toCrowdId:input.toCrowdId,fromZoneId:input.fromZoneId,toZoneId:input.toZoneId,fromAoeId:input.fromAoeId,toAoeId:input.toAoeId,from:input.from,to:input.to,category:input.category??"anchor",label:input.label||undefined,active:true,severed:false,presentationVisible:input.presentationVisible??true,presentationLabel:false,locked:false}}
export const tokenInitiativeDefault=(category:TacticalToken["category"])=>category!=="object";
export function normalizeInitiativeEntry(entry:InitiativeEntry):InitiativeEntry{return entry.targetType&&entry.targetId?entry:entry.tokenId?{...entry,targetType:"token",targetId:entry.tokenId}:entry}
export function initiativeTarget(state:TacticalState,entry:InitiativeEntry){const normalized=normalizeInitiativeEntry(entry);return normalized.targetType==="crowd"?state.crowdRegions.find(x=>x.id===normalized.targetId):normalized.targetType==="token"?state.tokens.find(x=>x.id===normalized.targetId):undefined}
export function initiativePortrait(state:TacticalState,entry:InitiativeEntry){const target=initiativeTarget(state,entry);return target&&"category" in target?{imageUrl:target.imageUrl,fallback:(target.name||target.category).slice(0,1).toUpperCase(),kind:"token" as const}:{fallback:"♟",kind:"crowd" as const}}
export const initiativeDisplayName=(state:TacticalState,entry:InitiativeEntry)=>initiativeTarget(state,entry)?.name??entry.name;
export function synchronizeInitiativeNames(state:TacticalState){state.initiative.entries=state.initiative.entries.map(entry=>{const normalized=normalizeInitiativeEntry(entry);return{...normalized,name:initiativeDisplayName(state,normalized)}});return state}
export function addInitiativeTarget(state:TacticalState,targetType:"token"|"crowd",targetId:string,initiative=10){if(state.initiative.entries.some(e=>{const n=normalizeInitiativeEntry(e);return n.targetType===targetType&&n.targetId===targetId}))return state;const target=targetType==="token"?state.tokens.find(x=>x.id===targetId):state.crowdRegions.find(x=>x.id===targetId);if(target)state.initiative.entries.push({id:crypto.randomUUID(),targetType,targetId,...(targetType==="token"?{tokenId:targetId}:{}),name:target.name,initiative,active:false});return state}
export function removeInitiativeTarget(state:TacticalState,targetType:"token"|"crowd",targetId:string){state.initiative.entries=state.initiative.entries.filter(e=>{const n=normalizeInitiativeEntry(e);return n.targetType!==targetType||n.targetId!==targetId});state.initiative.currentIndex=Math.max(0,Math.min(state.initiative.currentIndex,state.initiative.entries.length-1));return state}
export const tokenDistance=(a:Point,b:Point,gridSize:number,distancePerSquare:number)=>distance(a,b)/gridSize*distancePerSquare;
export type RulerState={status:"inactive"|"drawing"|"finished";points:Point[];preview?:Point;finished:boolean};
export const inactiveRuler=():RulerState=>({status:"inactive",points:[],finished:false});
export const startRuler=(point:Point):RulerState=>({status:"drawing",points:[point],preview:point,finished:false});
export const previewRuler=(ruler:RulerState,point:Point):RulerState=>ruler.status==="drawing"?{...ruler,preview:point}:ruler;
export const addRulerWaypoint=(ruler:RulerState,point:Point):RulerState=>ruler.status==="drawing"?{...ruler,points:[...ruler.points,point],preview:point}:ruler;
export const finishRuler=(ruler:RulerState):RulerState=>ruler.status==="drawing"?{...ruler,status:"finished",preview:undefined,finished:true}:ruler;
export const createPhaseMutation=(targetType:"family"|"object",targetId:string,id=crypto.randomUUID())=>({id,targetType,targetId,changes:{}});
export const updatePhaseMutation=(phase:EncounterPhase,id:string,changes:Partial<PhaseMutation>):EncounterPhase=>({...phase,mutations:(phase.mutations??[]).map(m=>m.id===id?{...m,...changes}:m)});
export const deletePhaseMutation=(phase:EncounterPhase,id:string):EncounterPhase=>({...phase,mutations:(phase.mutations??[]).filter(m=>m.id!==id)});
