import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { apiFetch } from "../lib/api";

type ArchiveKind = "faeo3" | "pixie";
type Work = { id:string; slug:string; title:string; summary?:string; description?:string; rating?:string; relationships?:string[]; characters?:string[]; charms?:string[]; warnings?:string[]; cycle?:string; status?:string; body?:string; authorNotes?:string; tags?:string[]; type?:string; images?:Array<{src:string;alt?:string;caption?:string}>; pixieSlug?:string; faeo3Slug?:string };
const flavor = ["wrong. also rude.", "you know me better than this", "why are you still clicking my things"];

function Markdown({ children }: { children: string }) {
  return <>{children.split(/\n\n+/).map((p, i) => <p key={i}>{p.split(/(\*\*[^*]+\*\*)/).map((part,j)=>part.startsWith("**")?<strong key={j}>{part.slice(2,-2)}</strong>:part)}</p>)}</>;
}
function Lock({ kind, onUnlock }: {kind:ArchiveKind;onUnlock:()=>void}) {
 const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(kind==="faeo3"?"if you found this, no you didn't.":"unfinished things live here. be nice."); const [attempt,setAttempt]=useState(0);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);const r=await apiFetch(`/api/secrets/lumi_${kind}/unlock`,{method:"POST",body:JSON.stringify({password})});if(r.ok)onUnlock();else{setMessage(flavor[attempt%flavor.length]);setAttempt(x=>x+1);setPassword("");}setBusy(false)}
 return <main className={`secret-lock secret-${kind}`}><section className="secret-lock-card"><p className="secret-kicker">LUMI TURNLEAF / PRIVATE</p><h1>{kind==="faeo3"?"PRIVATE JOURNAL >:(":"PRIVATE ART ACCOUNT"}</h1><p>{message}</p><form onSubmit={submit}><label>Password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" /></label><button disabled={busy}>{busy?"checking...":"Unlock"}</button></form><Link to="/directory/lumi-turnleaf">← put this back</Link></section></main>
}
function CrossLink({to,children}:{to:string;children:ReactNode}){return <Link className="secret-crosslink" to={to}>{children} →</Link>}
function Faeo3({works}:{works:Work[]}){const {slug}=useParams();const work=works.find(w=>w.slug===slug);if(work)return <main className="faeo3-site"><ArchiveHeader kind="faeo3"/><article className="faeo3-reading"><div className="faeo3-workhead"><h1>{work.title}</h1><dl><dt>Rating</dt><dd>{work.rating}</dd><dt>Warnings</dt><dd>{work.warnings?.join(", ")}</dd><dt>Relationships</dt><dd>{work.relationships?.join(", ")}</dd><dt>Characters</dt><dd>{work.characters?.join(", ")}</dd><dt>Charms</dt><dd>{work.charms?.join(", ")}</dd><dt>Status</dt><dd>{work.status}</dd></dl><h2>Summary</h2><p>{work.summary}</p><aside><strong>Author's note</strong><p>{work.authorNotes}</p></aside></div><section className="faeo3-prose"><Markdown>{work.body||""}</Markdown></section>{work.pixieSlug?<CrossLink to={`/secret/pixie/art/${work.pixieSlug}`}>Illustrations available on Pixie</CrossLink>:null}<nav className="secret-prevnext"><Link to="/secret/faeo3">← Tale index</Link></nav></article></main>;
 return <main className="faeo3-site"><ArchiveHeader kind="faeo3"/><section className="faeo3-index"><h1>Lumi Turnleaf's Tales</h1><p className="archive-private">A private grimoire. No Petals, Whispers, or public footprints are kept here.</p>{works.map(w=><article className="faeo3-listing" key={w.id}><h2><Link to={`/secret/faeo3/tales/${w.slug}`}>{w.title}</Link></h2><p className="faeo3-byline">by LumiTurnleaf · {w.status}</p><p>{w.summary}</p><ul className="charm-list">{[...(w.relationships||[]),...(w.characters||[]),...(w.charms||[])].map(x=><li key={x}>{x}</li>)}</ul></article>)}</section></main>
}
function ArchiveHeader({kind}:{kind:ArchiveKind}){return <header className="secret-site-header"><Link to={`/secret/${kind}`} className="secret-brand">{kind==="faeo3"?<>FAEO3 <small>Fae Archive of Our Own</small></>:<>Pixie <small>Lumi's private atelier</small></>}</Link><nav>{kind==="faeo3"?"Tales · Hoards · Keepsakes · Grimoire":"Illustrations · Manga · Sketches · Panel Drafts"}</nav><Link to="/directory/lumi-turnleaf">Return to FaeBook</Link></header>}
function Pixie({works}:{works:Work[]}){const {slug}=useParams();const work=works.find(w=>w.slug===slug);const [page,setPage]=useState(0);useEffect(()=>setPage(0),[slug]);if(work){const image=work.images?.[page];const at=works.indexOf(work);return <main className="pixie-site"><ArchiveHeader kind="pixie"/><article className="pixie-art"><div className="pixie-canvas"><img src={image?.src} alt={image?.alt||work.title}/><p>{image?.caption}</p>{(work.images?.length||0)>1?<div className="pixie-pages"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>← Previous page</button><span>{page+1} / {work.images?.length}</span><button disabled={page===(work.images?.length||1)-1} onClick={()=>setPage(p=>p+1)}>Next page →</button></div>:null}</div><aside><p className="pixie-type">{work.type}</p><h1>{work.title}</h1><p>{work.description}</p><div className="pixie-tags">{work.tags?.map(t=><span key={t}>#{t}</span>)}</div>{work.faeo3Slug?<CrossLink to={`/secret/faeo3/tales/${work.faeo3Slug}`}>Based on Tale #{works[at]?.id} on FAEO3</CrossLink>:null}<nav className="secret-prevnext">{at>0?<Link to={`/secret/pixie/art/${works[at-1].slug}`}>← Previous artwork</Link>:<span/>}{at<works.length-1?<Link to={`/secret/pixie/art/${works[at+1].slug}`}>Next artwork →</Link>:null}</nav></aside></article></main>}
 const groups=["illustration","manga","sketch","panel-draft"];return <main className="pixie-site"><ArchiveHeader kind="pixie"/><section className="pixie-profile"><div className="pixie-avatar">L</div><div><h1>Lumi Turnleaf</h1><p>private sketches, finished things, and things that are none of your business.</p></div></section><section className="pixie-gallery">{groups.map(g=>{const items=works.filter(w=>w.type===g);return items.length?<section key={g}><h2>{g.replace("panel-draft","Panel Drafts").replace(/^./,c=>c.toUpperCase())}</h2><div className="pixie-grid">{items.map(w=><Link to={`/secret/pixie/art/${w.slug}`} key={w.id}><img src={w.images?.[0]?.src} alt={w.images?.[0]?.alt||w.title}/><strong>{w.title}</strong><p>{w.tags?.map(t=>`#${t}`).join("  ")}</p></Link>)}</div></section>:null})}</section></main>
}
export default function SecretArchivePage({kind}:{kind:ArchiveKind}){const [state,setState]=useState<"loading"|"locked"|"open">("loading");const [works,setWorks]=useState<Work[]>([]);async function load(){const status=await apiFetch(`/api/secrets/lumi_${kind}/status`);if(!status.ok){setState("locked");return}const data=await status.json();if(!data.unlocked){setState("locked");return}const content=await apiFetch(`/api/secrets/lumi_${kind}/content`);if(!content.ok){setState("locked");return}setWorks((await content.json()).works||[]);setState("open")}useEffect(()=>{void load()},[kind]);if(state==="loading")return <main className={`secret-lock secret-${kind}`}><p>checking the wards...</p></main>;if(state==="locked")return <Lock kind={kind} onUnlock={()=>void load()}/>;return kind==="faeo3"?<Faeo3 works={works}/>:<Pixie works={works}/>}
