import { useCallback,useEffect,useRef,useState } from "react";
import { useParams } from "react-router-dom";
import TacticalBattlefield from "../components/tactical/TacticalBattlefield";
import { apiFetch } from "../lib/api";
import { createTacticalChannel,type TacticalMessage } from "../lib/tacticalBroadcast";
import { interpolatePreparedMorph } from "../lib/tacticalPolygons";
import { usePresentationViewBox } from "../hooks/usePresentationViewBox";
import type { Point,TacticalEncounter,TacticalState } from "../types/tactical";

export default function TacticalPresentationPage(){
 const {containerRef,viewBox}=usePresentationViewBox<HTMLElement>();
 const {encounterId=""}=useParams();const [encounter,setEncounter]=useState<TacticalEncounter|null>(null),[state,setState]=useState<TacticalState|null>(null),[connected,setConnected]=useState(false),[overlay,setOverlay]=useState(true),[crowdOverrides,setCrowdOverrides]=useState<Record<string,Point[]>>({});const timer=useRef<number|undefined>(undefined),crowdAnimations=useRef(new Map<string,{animationId:string;raf:number;current:Point[]}>());
 const load=useCallback(async()=>{const r=await apiFetch(`/api/dm/encounters/${encounterId}`),d=await r.json();if(!r.ok)throw new Error(d.error);setEncounter(d.encounter);setState(d.encounter.state)},[encounterId]);
 useEffect(()=>{const initialLoad=window.setTimeout(()=>void load(),0);const channel=createTacticalChannel(encounterId);if(!channel)return;channel.onmessage=(event:MessageEvent<TacticalMessage>)=>{setConnected(true);const message=event.data;if(message.type==="state")setState(current=>{if(!current)return message.state;if(current.presentation?.frozen&&message.state.presentation?.frozen)return {...current,presentation:{...current.presentation,blackout:!!message.state.presentation.blackout}};return message.state});if(message.type==="positions"||message.type==="token-group-position")setState(s=>s?{...s,tokens:s.tokens.map(t=>message.positions[t.id]?{...t,...message.positions[t.id]}:t)}:s);if(message.type==="aoe-transform")setState(s=>s?{...s,aoes:s.aoes.map(a=>a.id===message.id?{...a,...message.transform}:a)}:s);if(message.type==="camera-state")setState(s=>s?{...s,battlefield:{...s.battlefield,presentationCamera:message.camera}}:s);if(message.type==="polygon-preview")setState(s=>s?{...s,[message.kind==="zone"?"zones":"crowdRegions"]:(message.kind==="zone"?s.zones:s.crowdRegions).map(p=>p.id===message.id?{...p,points:message.points}:p)}:s);if(message.type==="crowd-surge-animation")setState(current=>{if(current?.presentation?.frozen)return current;const previous=crowdAnimations.current.get(message.id);if(previous)cancelAnimationFrame(previous.raf);const animationId=crypto.randomUUID(),morph={from:message.morphFrom,to:message.morphTo},started=performance.now(),animate=(now:number)=>{const animation=crowdAnimations.current.get(message.id);if(!animation||animation.animationId!==animationId)return;const progress=Math.min(1,(now-started)/message.durationMs),eased=1-Math.pow(1-progress,3),points=interpolatePreparedMorph(morph,eased);animation.current=points;if(progress<1){setCrowdOverrides(value=>({...value,[message.id]:points}));animation.raf=requestAnimationFrame(animate);return}const exactDestination=structuredClone(message.toPoints);animation.current=exactDestination;setCrowdOverrides(value=>({...value,[message.id]:exactDestination}));animation.raf=requestAnimationFrame(()=>{const latest=crowdAnimations.current.get(message.id);if(latest?.animationId!==animationId)return;crowdAnimations.current.delete(message.id);setCrowdOverrides(value=>Object.fromEntries(Object.entries(value).filter(([id])=>id!==message.id)))})};const raf=requestAnimationFrame(animate);crowdAnimations.current.set(message.id,{animationId,raf,current:message.fromPoints});return current});if(message.type==="hello")channel.postMessage({type:"presence"})};channel.postMessage({type:"hello"});return()=>{window.clearTimeout(initialLoad);channel.close()}},[encounterId,load]);
 function revealOverlay(){setOverlay(true);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setOverlay(false),3000)}
 if(!state)return <main className="presentation-loading">Preparing player display…</main>;
 const camera=state.battlefield.presentationCamera||{zoom:.75,panX:40,panY:40};
 return <main ref={containerRef} className={`tactical-presentation ${state.presentation?.blackout?"blackout":""}`} onPointerMove={revealOverlay} onKeyDown={revealOverlay}>{state.presentation?.blackout?<div className="blackout-card"><span>✦</span><h1>{encounter?.name}</h1></div>:<TacticalBattlefield state={state} crowdPointOverrides={crowdOverrides} mode="presentation" zoom={camera.zoom} pan={{x:camera.panX,y:camera.panY}} presentationViewport={viewBox} measurement={state.presentation?.measurement}/>}<div className={`presenter-overlay ${overlay?"visible":""}`}><span>{connected?"Live":"Waiting for DM"}</span><button onClick={()=>document.documentElement.requestFullscreen?.()}>Fullscreen</button><button onClick={()=>void load()}>Reconnect</button></div></main>
}
