import { useCallback,useEffect,useRef,useState } from "react";
import { useParams } from "react-router-dom";
import TacticalBattlefield from "../components/tactical/TacticalBattlefield";
import { usePresentationViewBox } from "../hooks/usePresentationViewBox";
import { apiFetch } from "../lib/api";
import { createTacticalChannel,type TacticalMessage } from "../lib/tacticalBroadcast";
import type { TacticalCamera } from "../lib/tacticalCoordinates";
import { interpolatePreparedMorph } from "../lib/tacticalPolygons";
import type { Point,TacticalEncounter,TacticalState } from "../types/tactical";

const DEFAULT_CAMERA:TacticalCamera={zoom:.75,panX:40,panY:40};
const MIN_ZOOM=.15,MAX_ZOOM=4;
const clampZoom=(zoom:number)=>Math.min(MAX_ZOOM,Math.max(MIN_ZOOM,zoom));

export default function TacticalPresentationPage(){
 const {containerRef,viewBox}=usePresentationViewBox<HTMLElement>();
 const {encounterId=""}=useParams();
 const storageKey=`faebook:tactical:presentation-camera:${encounterId}`;
 const [encounter,setEncounter]=useState<TacticalEncounter|null>(null),[state,setState]=useState<TacticalState|null>(null),[connected,setConnected]=useState(false),[overlay,setOverlay]=useState(true),[crowdOverrides,setCrowdOverrides]=useState<Record<string,Point[]>>({}),[localCamera,setLocalCamera]=useState<TacticalCamera|null>(null),[followDm,setFollowDm]=useState(true),[dragging,setDragging]=useState(false);
 const timer=useRef<number|undefined>(undefined),crowdAnimations=useRef(new Map<string,{animationId:string;raf:number;current:Point[]}>()),drag=useRef<{pointerId:number;x:number;y:number;camera:TacticalCamera}|null>(null),mainRef=useRef<HTMLElement|null>(null),followDmRef=useRef(true);
 const setRefs=useCallback((node:HTMLElement|null)=>{mainRef.current=node;containerRef(node)},[containerRef]);
 const revealOverlay=useCallback(()=>{setOverlay(true);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setOverlay(false),3000)},[]);
 const load=useCallback(async()=>{const r=await apiFetch(`/api/dm/encounters/${encounterId}`),d=await r.json();if(!r.ok)throw new Error(d.error);setEncounter(d.encounter);setState(d.encounter.state);setLocalCamera(current=>{if(current)return current;try{const saved=sessionStorage.getItem(storageKey);if(saved){const parsed=JSON.parse(saved) as TacticalCamera;if(Number.isFinite(parsed.zoom)&&Number.isFinite(parsed.panX)&&Number.isFinite(parsed.panY)){followDmRef.current=false;setFollowDm(false);return {...parsed,zoom:clampZoom(parsed.zoom)}}}}catch{/* Ignore malformed display-local camera data. */}return d.encounter.state.battlefield.presentationCamera??DEFAULT_CAMERA})},[encounterId,storageKey]);

 useEffect(()=>{const initialLoad=window.setTimeout(()=>void load(),0);const channel=createTacticalChannel(encounterId);if(!channel)return;channel.onmessage=(event:MessageEvent<TacticalMessage>)=>{setConnected(true);const message=event.data;if(message.type==="state"){if(followDmRef.current)setLocalCamera(message.state.battlefield.presentationCamera??DEFAULT_CAMERA);setState(current=>{if(!current)return message.state;if(current.presentation?.frozen&&message.state.presentation?.frozen)return {...current,presentation:{...current.presentation,blackout:!!message.state.presentation.blackout}};return message.state})}if(message.type==="positions"||message.type==="token-group-position")setState(s=>s?{...s,tokens:s.tokens.map(t=>message.positions[t.id]?{...t,...message.positions[t.id]}:t)}:s);if(message.type==="aoe-transform")setState(s=>s?{...s,aoes:s.aoes.map(a=>a.id===message.id?{...a,...message.transform}:a)}:s);if(message.type==="camera-state"){if(followDmRef.current)setLocalCamera(message.camera);setState(s=>s?{...s,battlefield:{...s.battlefield,presentationCamera:message.camera}}:s)}if(message.type==="polygon-preview")setState(s=>s?{...s,[message.kind==="zone"?"zones":"crowdRegions"]:(message.kind==="zone"?s.zones:s.crowdRegions).map(p=>p.id===message.id?{...p,points:message.points}:p)}:s);if(message.type==="crowd-surge-animation")setState(current=>{if(current?.presentation?.frozen)return current;const previous=crowdAnimations.current.get(message.id);if(previous)cancelAnimationFrame(previous.raf);const animationId=crypto.randomUUID(),morph={from:message.morphFrom,to:message.morphTo},started=message.startedAt??performance.now(),animate=(now:number)=>{const animation=crowdAnimations.current.get(message.id);if(!animation||animation.animationId!==animationId)return;const progress=Math.min(1,(now-started)/message.durationMs),eased=1-Math.pow(1-progress,3),points=interpolatePreparedMorph(morph,eased);animation.current=points;if(progress<1){setCrowdOverrides(value=>({...value,[message.id]:points}));animation.raf=requestAnimationFrame(animate);return}const exactDestination=structuredClone(message.toPoints);animation.current=exactDestination;setCrowdOverrides(value=>({...value,[message.id]:exactDestination}));animation.raf=requestAnimationFrame(()=>{const latest=crowdAnimations.current.get(message.id);if(latest?.animationId!==animationId)return;crowdAnimations.current.delete(message.id);setCrowdOverrides(value=>Object.fromEntries(Object.entries(value).filter(([id])=>id!==message.id)))})};const raf=requestAnimationFrame(animate);crowdAnimations.current.set(message.id,{animationId,raf,current:message.fromPoints});return current});if(message.type==="hello")channel.postMessage({type:"presence"})};channel.postMessage({type:"hello"});return()=>{window.clearTimeout(initialLoad);channel.close()}},[encounterId,load]);

 const dmCamera=state?.battlefield.presentationCamera??DEFAULT_CAMERA;
 useEffect(()=>{if(!localCamera)return;sessionStorage.setItem(storageKey,JSON.stringify(localCamera))},[localCamera,storageKey]);
 useEffect(()=>()=>{window.clearTimeout(timer.current);crowdAnimations.current.forEach(animation=>cancelAnimationFrame(animation.raf))},[]);

 const changeCamera=useCallback((update:(camera:TacticalCamera)=>TacticalCamera)=>{followDmRef.current=false;setFollowDm(false);setLocalCamera(current=>update(current??dmCamera));revealOverlay()},[dmCamera,revealOverlay]);
 const zoomAtCursor=useCallback((nextZoom:number,clientX?:number,clientY?:number)=>changeCamera(camera=>{const rect=mainRef.current?.getBoundingClientRect();const zoom=clampZoom(nextZoom);if(!rect)return {...camera,zoom};const point=clientX==null||clientY==null?{x:viewBox.x+viewBox.width/2,y:viewBox.y+viewBox.height/2}:{x:viewBox.x+(clientX-rect.left)*viewBox.width/rect.width,y:viewBox.y+(clientY-rect.top)*viewBox.height/rect.height};const world={x:(point.x-camera.panX)/camera.zoom,y:(point.y-camera.panY)/camera.zoom};return {zoom,panX:point.x-world.x*zoom,panY:point.y-world.y*zoom}}),[changeCamera,viewBox]);
 const fitMap=useCallback(()=>changeCamera(()=>{const battlefield=state!.battlefield,zoom=clampZoom(Math.min(viewBox.width/battlefield.width,viewBox.height/battlefield.height));return {zoom,panX:viewBox.x+(viewBox.width-battlefield.width*zoom)/2,panY:viewBox.y+(viewBox.height-battlefield.height*zoom)/2}}),[changeCamera,state,viewBox]);
 const dmView=useCallback(()=>{setLocalCamera(dmCamera);followDmRef.current=true;setFollowDm(true);revealOverlay()},[dmCamera,revealOverlay]);

 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.target as HTMLElement)?.matches("button,input,select,textarea"))return;const camera=localCamera??dmCamera,step=40;switch(event.key.toLowerCase()){case"arrowleft":changeCamera(c=>({...c,panX:c.panX+step}));break;case"arrowright":changeCamera(c=>({...c,panX:c.panX-step}));break;case"arrowup":changeCamera(c=>({...c,panY:c.panY+step}));break;case"arrowdown":changeCamera(c=>({...c,panY:c.panY-step}));break;case"+":case"=":zoomAtCursor(camera.zoom*1.1);break;case"-":zoomAtCursor(camera.zoom/1.1);break;case"f":fitMap();break;case"d":dmView();break;default:return}event.preventDefault();revealOverlay()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[changeCamera,dmCamera,dmView,fitMap,localCamera,revealOverlay,zoomAtCursor]);

 if(!state||!localCamera)return <main className="presentation-loading">Preparing player display…</main>;
 return <main ref={setRefs} className={`tactical-presentation ${state.presentation?.blackout?"blackout":""} ${dragging?"camera-dragging":""}`} onPointerMove={event=>{revealOverlay();const active=drag.current;if(!active||active.pointerId!==event.pointerId)return;const rect=mainRef.current!.getBoundingClientRect(),scaleX=viewBox.width/rect.width,scaleY=viewBox.height/rect.height;setLocalCamera({...active.camera,panX:active.camera.panX+(event.clientX-active.x)*scaleX,panY:active.camera.panY+(event.clientY-active.y)*scaleY})}} onPointerDown={event=>{if(event.button!==0&&event.button!==1)return;if((event.target as Element).closest(".presenter-overlay"))return;event.preventDefault();followDmRef.current=false;setFollowDm(false);drag.current={pointerId:event.pointerId,x:event.clientX,y:event.clientY,camera:localCamera};event.currentTarget.setPointerCapture(event.pointerId);setDragging(true);revealOverlay()}} onPointerUp={event=>{if(drag.current?.pointerId!==event.pointerId)return;drag.current=null;setDragging(false);event.currentTarget.releasePointerCapture(event.pointerId)}} onPointerCancel={()=>{drag.current=null;setDragging(false)}} onWheel={event=>{event.preventDefault();zoomAtCursor(localCamera.zoom*(event.deltaY>0?.9:1.1),event.clientX,event.clientY)}}>{state.presentation?.blackout?<div className="blackout-card"><span>✦</span><h1>{encounter?.name}</h1></div>:<TacticalBattlefield state={state} crowdPointOverrides={crowdOverrides} mode="presentation" zoom={localCamera.zoom} pan={{x:localCamera.panX,y:localCamera.panY}} presentationViewport={viewBox} measurement={state.presentation?.measurement}/>}<div className={`presenter-overlay ${overlay?"visible":""}`}><span>{connected?"Live":"Waiting for DM"}</span><button aria-label="Zoom out" onClick={()=>zoomAtCursor(localCamera.zoom/1.1)}>−</button><output>{Math.round(localCamera.zoom*100)}%</output><button aria-label="Zoom in" onClick={()=>zoomAtCursor(localCamera.zoom*1.1)}>+</button><button onClick={fitMap}>Fit Map</button><button onClick={dmView}>DM View</button><label className="follow-dm-camera"><input type="checkbox" checked={followDm} onChange={event=>{followDmRef.current=event.target.checked;setFollowDm(event.target.checked);if(event.target.checked)setLocalCamera(dmCamera);revealOverlay()}}/> Follow DM Camera</label><button onClick={()=>document.documentElement.requestFullscreen?.()}>Fullscreen</button><button onClick={()=>void load()}>Reconnect</button></div></main>
}
