import { useState, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import SecretLoginForm from "./SecretLoginForm";

type Work = { slug: string; title: string; summary: string; rating: string; relationships: string[]; characters: string[]; charms: string[]; warnings: string[]; status: string; authorNotes: string; body: string };

const works: Work[] = [
  { slug: "the-moon-kept-her-name", title: "The Moon Kept Her Name", summary: "A knight follows a stolen name through three moonlit courts.", rating: "Teen Dewdrops", relationships: ["The Knight/The Thorn Witch"], characters: ["The Knight", "The Thorn Witch", "A Very Suspicious Moth"], charms: ["yearning", "moon bargains", "enemies to reluctant co-conspirators"], warnings: ["No archive warnings apply"], status: "complete", authorNotes: "i wrote this instead of sleeping. the moth is important, obviously.", body: "The moon had misplaced her name again.\n\nAt the edge of the briar court, the Knight found it caught on a thorn: three silver syllables trembling like rain. She should have returned them. Instead, she closed her gauntlet around the light.\n\nThe Thorn Witch was waiting beneath the oldest arch. **‘You took your time,’** she said, as though the Knight had not crossed a forest that rearranged itself whenever she blinked.\n\nSome bargains begin with a kiss. The dangerous ones begin with directions." },
  { slug: "seven-ways-to-hide-a-crown", title: "Seven Ways to Hide a Crown", summary: "Six terrible plans and one that might work.", rating: "Mature Moonlight", relationships: ["Princess & Her Catastrophic Decisions"], characters: ["The Briar Princess", "Glasswing"], charms: ["unreliable narrator", "court intrigue", "draft", "someone gets stabbed eventually"], warnings: ["Creator chose not to use warnings"], status: "draft", authorNotes: "DRAFT. do not perceive the bracketed bit. i mean it.", body: "First: beneath the lake, where every drowned promise grows a pearl.\n\nSecond: inside the royal portrait, behind the painted version of her smile.\n\nThird: **[LUMI FIX THIS PART]**\n\nGlasswing knocked the crown from the table with one immaculate paw. Perhaps, the princess thought, there were eight ways." },
];

function Header() { return <header className="faeo3-archive-header"><Link to="/secret/faeo3" className="faeo3-archive-brand"><strong>FaeO3</strong><small>Fae Archive of Our Own</small></Link><nav aria-label="Archive navigation">Tales · Hoards · Keepsakes · Grimoire</nav></header>; }
function Markdown({ children }: { children: string }) { return <>{children.split(/\n\n+/).map((paragraph, index) => <p key={index}>{paragraph.split(/(\*\*[^*]+\*\*)/).map((part, partIndex) => part.startsWith("**") ? <strong key={partIndex}>{part.slice(2, -2)}</strong> : part)}</p>)}</>; }
function Tags({ children }: { children: ReactNode }) { return <li>{children}</li>; }

function Archive() {
  const { slug } = useParams();
  const work = works.find((item) => item.slug === slug);
  if (work) return <main className="secret-site-page faeo3-site"><Header /><article className="faeo3-reading"><h1>{work.title}</h1><dl><dt>Rating</dt><dd>{work.rating}</dd><dt>Warnings</dt><dd>{work.warnings.join(", ")}</dd><dt>Relationships</dt><dd>{work.relationships.join(", ")}</dd><dt>Characters</dt><dd>{work.characters.join(", ")}</dd><dt>Charms</dt><dd>{work.charms.join(", ")}</dd><dt>Status</dt><dd>{work.status}</dd></dl><section className="faeo3-summary"><h2>Summary</h2><p>{work.summary}</p><aside><strong>Author's note</strong><p>{work.authorNotes}</p></aside></section><section className="faeo3-prose"><Markdown>{work.body}</Markdown></section><Link to="/secret/faeo3">← Tale index</Link></article></main>;
  return <main className="secret-site-page faeo3-site"><Header /><section className="faeo3-index"><h1>Lumi Turnleaf's Tales</h1><p className="archive-private">A private grimoire. No Petals, Whispers, or public footprints are kept here.</p>{works.map((item) => <article className="faeo3-listing" key={item.slug}><h2><Link to={`/secret/faeo3/tales/${item.slug}`}>{item.title}</Link></h2><p className="faeo3-byline">by LumiTurnleaf · {item.status}</p><p>{item.summary}</p><ul className="charm-list">{[...item.relationships, ...item.characters, ...item.charms].map((tag) => <Tags key={tag}>{tag}</Tags>)}</ul></article>)}</section></main>;
}

export default function FaeO3Page() {
  const [unlocked, setUnlocked] = useState(false);
  if (unlocked) return <Archive />;
  return <main className="secret-site-page faeo3-login-site"><header className="faeo3-login-header"><div className="faeo3-identity-row"><div className="faeo3-logo"><strong>FaeO3</strong><span>Fae Archive of Our Own</span></div><span className="faeo3-login-context">Log in to FaeO3</span></div><div className="faeo3-navigation-row"><nav aria-label="Archive navigation"><span>Fandoms</span><span>Browse</span><span>Search</span><span>About</span></nav><label className="faeo3-search"><span className="sr-only">Search</span><input type="search" /></label></div></header><div className="faeo3-login-layout"><aside className="faeo3-categories"><h2>Find your favorites</h2><ul>{["All Fandoms", "Anime & Manga", "Books & Literature", "Music & Performers", "Original Works", "Other Media"].map((category) => <li key={category}>{category}</li>)}</ul></aside><section className="faeo3-welcome"><p className="faeo3-intro">A non-profit, non-commercial archive for transformative fanworks, created by and for fans.</p><div className="faeo3-account-panel"><h1>Log in to FaeO3</h1><p>With a FaeO3 account, you can:</p><ul><li>Post and organize your fanworks</li><li>Bookmark works you want to revisit</li><li>Subscribe to authors and series</li><li>Keep private works private</li></ul><SecretLoginForm siteName="faeo3" password="crackship" onUnlock={() => setUnlocked(true)} /></div></section></div></main>;
}
