import test from 'node:test';
import assert from 'node:assert/strict';
import { applyFamilyMutation, applyPhase, applyThresholdRules, createCheckpointGate, createPhaseMutation, createTether, deleteFamily, deletePhaseMutation, commitHistory, createCheckpoint, detectStacks, fanOut, insertVertex, isAirborne, measurementClick, measurementPointerMove, moveSelections, objectAltitude, rulerDistance, moveTetherEndpoint, moveVertex, objectsInRect, redoHistory, removeVertex, repairFamilyMembership, resizeAoe, rotateAoe, saveCrowdSurgePreset, setFamilyMembership, setObjectAltitude, tacticalObjectLabel, triggerCrowdSurgePreset, initiativePortrait, startRuler, addRulerWaypoint, finishRuler, tokenDistance, updatePhaseMutation, selectionsInRect, toggleSelection, translatePoints, undoHistory, waypointDistance } from '../src/lib/tacticalInteractions.ts';
import { interpolatePreparedMorph, normalizePolygonArea, polygonArea, preparePolygonMorph, resamplePolygon, signedPolygonArea } from '../src/lib/tacticalPolygons.ts';
import { presentationViewBox } from '../src/lib/tacticalPresentationConstants.ts';
import type { TacticalAoe, TacticalState } from '../src/types/tactical.ts';
const point={x:0,y:0};
const aoe=(shape:TacticalAoe['shape']):TacticalAoe=>({id:shape,name:shape,shape,x:0,y:0,size:10,active:true});
const state=():TacticalState=>({battlefield:{width:100,height:100,backgroundImageUrl:'',imageScale:1,imageX:0,imageY:0,gridVisible:true,snapEnabled:false,gridSize:10,gridOffsetX:0,gridOffsetY:0,distancePerSquare:5,unit:'ft'},tokens:[{id:'t',name:'T',x:10,y:10,size:10,category:'player',conditions:[],visible:true,familyId:'f'}],initiative:{round:1,currentIndex:0,manualOrder:false,entries:[]},phases:[],activePhaseId:null,families:[{id:'f',name:'F',memberIds:['t','a'],active:true}],zones:[],crowdRegions:[],tethers:[],spotlights:[],aoes:[{...aoe('circle'),id:'a',familyId:'f'}],annotations:[],events:[],eventLog:[]});
test('presentation viewport preserves the base frame and expands for container aspect ratios',()=>{
 assert.deepEqual(presentationViewBox(1920,1080),{x:0,y:0,width:1920,height:1080});
 assert.deepEqual(presentationViewBox(1600,900),{x:0,y:0,width:1920,height:1080});
 const hd=presentationViewBox(1366,768);assert.equal(hd.height,1080);assert.ok(hd.width>1920);assert.ok(hd.x<0);
 const tall=presentationViewBox(1300,1000);assert.equal(tall.width,1920);assert.ok(Math.abs(tall.height-1476.923)<.001);assert.ok(Math.abs(tall.y+198.462)<.001);
 const portrait=presentationViewBox(900,1200);assert.deepEqual(portrait,{x:0,y:-740,width:1920,height:2560});
 const wide=presentationViewBox(2400,1080);assert.deepEqual(wide,{x:-240,y:0,width:2400,height:1080});
});
test('polygon operations preserve order and minimum validity',()=>{const p=[point,{x:10,y:0},{x:10,y:10}];assert.deepEqual(moveVertex(p,1,{x:5,y:1})[1],{x:5,y:1});assert.deepEqual(insertVertex(p,0)[1],{x:5,y:0});assert.equal(removeVertex(p,0).length,3);assert.deepEqual(translatePoints(p,{x:2,y:3})[0],{x:2,y:3})});
test('AoE resize supports circle and ring radius',()=>{assert.equal(resizeAoe(aoe('circle'),{x:3,y:4}).size,5);assert.equal(resizeAoe({...aoe('ring'),innerRadius:4},{x:0,y:20}).innerRadius,4)});
test('AoE resize supports cone radius',()=>assert.equal(resizeAoe(aoe('cone'),{x:0,y:20}).size,20));
test('line resize preserves length and width semantics',()=>assert.deepEqual(({size:resizeAoe(aoe('line'),{x:30,y:5}).size,width:resizeAoe(aoe('line'),{x:30,y:5}).width}),{size:30,width:10}));
test('square resize stays square',()=>{const a=resizeAoe(aoe('square'),{x:12,y:20});assert.equal(a.size,40);assert.equal(a.width,40)});
test('rectangle resize has independent dimensions',()=>{const a=resizeAoe(aoe('rectangle'),{x:12,y:20});assert.deepEqual({size:a.size,width:a.width},{size:24,width:40})});
test('directional AoE rotation follows pointer',()=>assert.equal(Math.round(rotateAoe(aoe('cone'),{x:0,y:10}).rotation!),90));
test('rectangle selection includes tactical kinds',()=>{const s=state();s.zones.push({id:'z',name:'Z',kind:'hazard',points:[{x:5,y:5},{x:8,y:5},{x:8,y:8}],active:true,visible:true});assert.deepEqual(new Set(objectsInRect(s,{x:0,y:0},{x:20,y:20})),new Set(['t','a','z']));assert.equal(selectionsInRect(s,{x:0,y:0},{x:20,y:20}).length,3)});
test('modifier selection toggles membership',()=>{const a={kind:'token' as const,id:'a'};assert.equal(toggleSelection([a],a,true).length,0);assert.equal(toggleSelection([],a,true).length,1)});
test('group movement respects locks',()=>{const s=state();s.aoes[0].locked=true;moveSelections(s,[{kind:'token',id:'t'},{kind:'aoe',id:'a'}],{x:5,y:7});assert.deepEqual({x:s.tokens[0].x,y:s.tokens[0].y},{x:15,y:17});assert.equal(s.aoes[0].x,0)});
test('stack detection and fan out do not mutate coordinates',()=>{const p=[{id:'a',x:1,y:1},{id:'b',x:2,y:2}];assert.deepEqual(detectStacks(p,3),[['a','b']]);assert.equal(Object.keys(fanOut(point,['a','b'])).length,2);assert.deepEqual(p[0],{id:'a',x:1,y:1})});
test('waypoint distance is calibrated and cumulative',()=>assert.equal(waypointDistance([point,{x:30,y:40},{x:60,y:40}],10,5),40));
test('standard measurement completes on the second click and a third click starts fresh',()=>{let measurement=measurementClick(null,{x:0,y:0});measurement=measurementPointerMove(measurement,{x:30,y:40});assert.deepEqual(measurement,{status:'drawing',start:{x:0,y:0},preview:{x:30,y:40,altitude:0}});measurement=measurementClick(measurement,{x:30,y:40});assert.deepEqual(measurement,{status:'finished',start:{x:0,y:0},end:{x:30,y:40}});assert.equal(waypointDistance([measurement.start,measurement.end],10,5),25);assert.equal(measurementPointerMove(measurement,{x:99,y:99}),measurement);measurement=measurementClick(measurement,{x:5,y:6});assert.deepEqual(measurement,{status:'drawing',start:{x:5,y:6},preview:{x:5,y:6}})});
test('altitude defaults, controls, landing, locking, and undo preserve vertical state',()=>{const legacy:{altitude?:number;locked?:boolean}={};assert.equal(objectAltitude(legacy),0);assert.equal(isAirborne(legacy),false);setObjectAltitude(legacy,5);setObjectAltitude(legacy,10);assert.equal(legacy.altitude,10);assert.equal(isAirborne(legacy),true);setObjectAltitude(legacy,0);assert.equal(legacy.altitude,0);assert.equal(isAirborne(legacy),false);legacy.locked=true;setObjectAltitude(legacy,30);assert.equal(legacy.altitude,0);const before=state(),after=structuredClone(before);after.tokens[0].altitude=40;const history=commitHistory({past:[],present:before,future:[]},after);assert.equal(history.present.tokens[0].altitude,40);assert.equal(objectAltitude(undoHistory(history).present.tokens[0]),0)});
test('3D ruler handles Pythagorean, equal-altitude, free endpoints, and multiple segments',()=>{const pythag=rulerDistance([{x:0,y:0,altitude:0},{x:80,y:0,altitude:30}],10,5,'3d');assert.deepEqual(pythag,{horizontal:40,vertical:30,distance:50});const equal2d=rulerDistance([{x:0,y:0,altitude:20},{x:60,y:80,altitude:20}],10,5,'2d'),equal3d=rulerDistance([{x:0,y:0,altitude:20},{x:60,y:80,altitude:20}],10,5,'3d');assert.equal(equal2d.distance,equal3d.distance);const free=measurementClick(null,{x:4,y:5});assert.equal(free?.status==='drawing'?objectAltitude(free.start):-1,0);const multi=rulerDistance([{x:0,y:0,altitude:0},{x:80,y:0,altitude:30},{x:80,y:60,altitude:30}],10,5,'3d');assert.equal(multi.distance,80)});
test('threshold rules only return enabled matching mutations',()=>assert.deepEqual(applyThresholdRules(3,[{id:'a',name:'A',enabled:true,comparison:'at-least',threshold:3,mutation:{active:true}},{id:'b',name:'B',enabled:false,comparison:'below',threshold:4,mutation:{active:false}}]),[{active:true}]));
test('family mutation propagates and updates family',()=>{const s=state();applyFamilyMutation(s,'f',{active:false,presentationVisible:false,locked:true});assert.equal(s.families[0].active,false);assert.equal(s.tokens[0].locked,true);assert.equal(s.aoes[0].active,false)});
test('phase applies family and object mutations',()=>{const s=state();applyPhase(s,{id:'p',name:'P',mutations:[{id:'1',targetType:'family',targetId:'f',changes:{locked:true}},{id:'2',targetType:'object',targetId:'t',changes:{presentationVisible:false}}]});assert.equal(s.activePhaseId,'p');assert.equal(s.tokens[0].locked,true);assert.equal(s.tokens[0].presentationVisible,false)});
test('checkpoint is an isolated state clone',()=>{const s=state(),c=createCheckpoint(s,'before','id','now');s.tokens[0].x=50;assert.equal(c.state.tokens[0].x,10)});
test('drag history undo and redo preserve exact endpoints',()=>{const before=state(),after=structuredClone(before);after.tokens[0].x=90;let h=commitHistory({past:[],present:before,future:[]},after);h=undoHistory(h);assert.equal(h.present.tokens[0].x,10);h=redoHistory(h);assert.equal(h.present.tokens[0].x,90)});

test('family state mirrors active, presentation, and lock mutations',()=>{const s=state();applyFamilyMutation(s,'f',{active:false,presentationVisible:false,locked:true});assert.deepEqual({active:s.families[0].active,presentationVisible:s.families[0].presentationVisible,locked:s.families[0].locked},{active:false,presentationVisible:false,locked:true});applyFamilyMutation(s,'f',{presentationVisible:true,locked:false});assert.equal(s.families[0].presentationVisible,true);assert.equal(s.families[0].locked,false)});
test('family reassignment and removal remain bidirectionally synchronized',()=>{const s=state();s.families.push({id:'g',name:'G',memberIds:[],active:true});setFamilyMembership(s,'t','g');assert.equal(s.tokens[0].familyId,'g');assert.equal(s.families[0].memberIds.includes('t'),false);assert.deepEqual(s.families[1].memberIds,['t']);setFamilyMembership(s,'t');assert.equal(s.tokens[0].familyId,undefined);assert.equal(s.families[1].memberIds.length,0)});
test('multi-object family assignment is complete and duplicate safe',()=>{const s=state();['t','a','t'].forEach(id=>setFamilyMembership(s,id,'f'));assert.deepEqual(new Set(s.families[0].memberIds),new Set(['t','a']));deleteFamily(s,'f');assert.equal(s.tokens[0].familyId,undefined);assert.equal(s.aoes[0].familyId,undefined)});
test('family repair resolves stale relationship data',()=>{const s=state();s.families[0].memberIds=['missing','t','t'];s.aoes[0].familyId=undefined;repairFamilyMembership(s);assert.deepEqual(s.families[0].memberIds,['t']);assert.equal(s.aoes[0].familyId,undefined)});
test('selected group can preserve existing membership and locks',()=>{const s=state();s.aoes[0].locked=true;moveSelections(s,[{kind:'token',id:'t'},{kind:'aoe',id:'a'}],{x:10,y:10});assert.equal(s.tokens[0].x,20);assert.equal(s.aoes[0].x,0)});
test('free tether endpoint moves but attached and locked endpoints do not',()=>{const s=state();s.tethers=[{id:'x',category:'binding',active:true,from:{x:0,y:0},to:{x:1,y:1}}];moveTetherEndpoint(s,'x','from',{x:5,y:6});assert.deepEqual(s.tethers[0].from,{x:5,y:6});s.tethers[0].fromTokenId='t';moveTetherEndpoint(s,'x','from',{x:9,y:9});assert.deepEqual(s.tethers[0].from,{x:5,y:6});s.tethers[0].locked=true;moveTetherEndpoint(s,'x','to',{x:9,y:9});assert.deepEqual(s.tethers[0].to,{x:1,y:1})});
test('waypoint authoring and hover distance stay calibrated',()=>{let r=startRuler({x:0,y:0});r=addRulerWaypoint(r,{x:30,y:40});r=finishRuler(r);assert.equal(r.finished,true);assert.equal(waypointDistance(r.points,10,5),25);assert.equal(tokenDistance({x:0,y:0},{x:6,y:8},10,5),5)});
test('phase mutation authoring supports create update delete',()=>{let p={id:'p',name:'P',mutations:[createPhaseMutation('object','t','m')]};p=updatePhaseMutation(p,'m',{changes:{locked:true}});assert.equal(p.mutations?.[0].changes.locked,true);p=deletePhaseMutation(p,'m');assert.equal(p.mutations?.length,0)});
test('checkpoint gate creates at most once despite repeated movement',()=>{const before=state(),after=structuredClone(before),gate=createCheckpointGate();after.tokens[0].x++;assert.equal(gate.shouldCreate(before,before),false);assert.equal(gate.shouldCreate(before,after),true);gate.markCreated();for(let i=0;i<20;i++){after.tokens[0].x++;assert.equal(gate.shouldCreate(before,after),false)}});

test('tether creation supports attached and free endpoints with safe defaults',async()=>{
 const {createTether}=await import('../src/lib/tacticalInteractions.ts');
 const attached=createTether({fromTokenId:'willow',toTokenId:'north'},'tt');
 assert.deepEqual({from:attached.fromTokenId,to:attached.toTokenId,category:attached.category,active:attached.active,severed:attached.severed,shown:attached.presentationVisible,label:attached.presentationLabel,locked:attached.locked},{from:'willow',to:'north',category:'anchor',active:true,severed:false,shown:true,label:false,locked:false});
 const mixed=createTether({fromTokenId:'willow',to:{x:4,y:5}},'mixed');assert.deepEqual(mixed.to,{x:4,y:5});
 const free=createTether({from:{x:1,y:2},to:{x:3,y:4}},'free');assert.deepEqual([free.from,free.to],[{x:1,y:2},{x:3,y:4}]);
});
test('initiative defaults exclude objects and include combatant categories',async()=>{const {tokenInitiativeDefault}=await import('../src/lib/tacticalInteractions.ts');assert.equal(tokenInitiativeDefault('object'),false);for(const type of ['player','ally','enemy','boss'] as const)assert.equal(tokenInitiativeDefault(type),true)});
test('initiative linked names, legacy references, manual names, and target membership work',async()=>{const {addInitiativeTarget,initiativeDisplayName,initiativeTarget,normalizeInitiativeEntry,removeInitiativeTarget,synchronizeInitiativeNames}=await import('../src/lib/tacticalInteractions.ts');const s=state();s.crowdRegions.push({id:'c',name:'Crowd',points:[point,{x:1,y:0},{x:1,y:1}],state:'idle',active:true});const legacy={id:'i',tokenId:'t',name:'Old',initiative:12,active:false};s.initiative.entries=[legacy];assert.deepEqual(normalizeInitiativeEntry(legacy).targetId,'t');s.tokens[0].name='Idol Willow';assert.equal(initiativeDisplayName(s,legacy),'Idol Willow');synchronizeInitiativeNames(s);assert.equal(s.initiative.entries[0].name,'Idol Willow');const manual={id:'m',name:'Lair action',initiative:20,active:false};assert.equal(initiativeDisplayName(s,manual),'Lair action');addInitiativeTarget(s,'crowd','c',9);assert.equal(initiativeTarget(s,s.initiative.entries[1])?.id,'c');removeInitiativeTarget(s,'crowd','c');assert.equal(s.crowdRegions.length,1);removeInitiativeTarget(s,'token','t');assert.equal(s.tokens.length,1)});
test('finished ruler is immutable until a new measurement replaces it',()=>{let r=startRuler(point);r=addRulerWaypoint(r,{x:2,y:2});r=finishRuler(r);assert.equal(r.status,'finished');assert.equal(addRulerWaypoint(r,{x:9,y:9}),r);assert.deepEqual(startRuler({x:5,y:5}).points,[{x:5,y:5}])});
test('player label override preserves token and DM labels while global off wins',async()=>{const {tokenLabelIsPresented}=await import('../src/lib/tacticalPresentation.ts');const s=state(),t=s.tokens[0];s.presentation={frozen:false,blackout:false,layers:{background:true,grid:true,tokens:true,tokenLabels:'full',hpBars:true,conditions:true,defeatedTokens:true,zones:true,crowdRegions:true,strings:true,spotlights:true,aoes:true,annotations:true}};assert.equal(tokenLabelIsPresented(t,s,'presentation'),true);t.presentationLabelVisible=false;assert.equal(tokenLabelIsPresented(t,s,'presentation'),false);assert.equal(tokenLabelIsPresented(t,s,'dm'),true);assert.equal(s.tokens.includes(t),true);t.presentationLabelVisible=undefined;s.presentation.layers.tokenLabels='off';assert.equal(tokenLabelIsPresented(t,s,'presentation'),false)});
test('family and phase mutations propagate player label visibility',()=>{const s=state();applyFamilyMutation(s,'f',{presentationLabelVisible:false});assert.equal(s.tokens[0].presentationLabelVisible,false);applyPhase(s,{id:'labels',name:'Labels',mutations:[{id:'x',targetType:'family',targetId:'f',changes:{presentationLabelVisible:true}}]});assert.equal(s.tokens[0].presentationLabelVisible,true)});
test('protected mutation waits for checkpoint completion',async()=>{const {checkpointBeforeMutation}=await import('../src/lib/tacticalInteractions.ts');const order:string[]=[];await checkpointBeforeMutation(async()=>{await Promise.resolve();order.push('checkpoint')},()=>order.push('mutation'));assert.deepEqual(order,['checkpoint','mutation'])});

test('polygon math prepares stable, aligned morph correspondence once',()=>{const square=[point,{x:10,y:0},{x:10,y:10},{x:0,y:10}],wide=[point,{x:20,y:0},{x:20,y:2},{x:0,y:2}];assert.equal(polygonArea(square),100);assert.ok(Math.abs(polygonArea(normalizePolygonArea(wide,100))-100)<.001);assert.equal(resamplePolygon(square,7).length,7);const reversedRotated=[{x:10,y:10},{x:10,y:0},point,{x:0,y:10}],morph=preparePolygonMorph(square,reversedRotated);assert.equal(morph.from.length,32);assert.equal(Math.sign(signedPolygonArea(morph.from)),Math.sign(signedPolygonArea(morph.to)));assert.deepEqual(interpolatePreparedMorph(morph,0),morph.from);assert.deepEqual(interpolatePreparedMorph(morph,1),morph.to);assert.deepEqual(morph.from,morph.to)});
test('prepared morphs stay finite across unlike authored polygons and never replace the authored destination',()=>{const shapes=[[point,{x:12,y:0},{x:12,y:8},{x:0,y:8}],[{x:20,y:2},{x:28,y:4},{x:34,y:9},{x:29,y:11},{x:24,y:10},{x:21,y:16},{x:18,y:10},{x:14,y:8},{x:17,y:5}],[{x:-4,y:0},{x:14,y:0},{x:8,y:2},{x:14,y:18},{x:-4,y:18}]];for(const [from,to] of [[shapes[0],shapes[1]],[shapes[1],shapes[2]],[shapes[2],shapes[1]]] as const){const authored=structuredClone(to),morph=preparePolygonMorph(from,to);for(const progress of [.99,1])assert.ok(interpolatePreparedMorph(morph,progress).every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));assert.equal(morph.from.length,32);assert.equal(morph.to.length,32);assert.deepEqual(to,authored);assert.notDeepEqual(morph.to,authored)}});
test('saved and triggered surge presets retain compatibility and undo exact points',()=>{const s=state(),original=[point,{x:10,y:0},{x:10,y:10},{x:0,y:10}];s.crowdRegions=[{id:'c',name:'South Crowd',points:structuredClone(original),state:'idle',active:true,surges:[{id:'legacy',origin:point,direction:90,distance:5,pressure:2,createdAt:'then'}]}];assert.equal(s.crowdRegions[0].surgePresets,undefined);const preset=saveCrowdSurgePreset(s,'c',{id:'p',name:'South Crush',points:[{x:20,y:20},{x:40,y:20},{x:40,y:25},{x:20,y:25}],createdAt:'now'});assert.equal(s.crowdRegions[0].surges?.[0].id,'legacy');const before=structuredClone(s),history=commitHistory({past:[],present:before,future:[]},triggerCrowdSurgePreset(structuredClone(s),'c',preset.id));assert.deepEqual(history.present.crowdRegions[0].points,preset.points);assert.deepEqual(undoHistory(history).present.crowdRegions[0].points,original)});
test('surge draft operations can change vertex count without touching the live crowd before save',()=>{const s=state(),live=[point,{x:20,y:0},{x:20,y:20},{x:0,y:20}];s.crowdRegions=[{id:'south',name:'Crowd Region S',points:structuredClone(live),state:'idle',active:true}];let draft=structuredClone(live);draft=moveVertex(draft,1,{x:170,y:10});draft=insertVertex(draft,1);draft=translatePoints(draft,{x:5,y:-3});draft=removeVertex(draft,0);assert.deepEqual(s.crowdRegions[0].points,live);const preset=saveCrowdSurgePreset(s,'south',{id:'south-crush',name:'South Crush',points:draft});assert.equal(preset.points.length,draft.length);assert.deepEqual(s.crowdRegions[0].points,live);const edited=saveCrowdSurgePreset(s,'south',{id:preset.id,name:'South Crush Revised',points:insertVertex(preset.points,0)});assert.equal(s.crowdRegions[0].surgePresets?.length,1);assert.equal(edited.points.length,preset.points.length+1);assert.deepEqual(s.crowdRegions[0].points,live)});
test('family labels and initiative portraits resolve useful display data',()=>{const s=state();s.tokens[0].name='Straw Doll 4';s.tokens[0].imageUrl='/doll.png';assert.deepEqual(tacticalObjectLabel(s,'t'),{label:'Straw Doll 4',type:'Token'});assert.deepEqual(tacticalObjectLabel(s,'missing'),{label:'Unknown object',type:'Legacy'});const entry={id:'i',tokenId:'t',name:'old',initiative:10,active:false};assert.equal(initiativePortrait(s,entry).imageUrl,'/doll.png')});

test('crowd baselines initialize once and survive multiple surge transitions',async()=>{
 const {ensureCrowdOriginals,returnCrowdToOriginal,setCrowdOriginal}=await import('../src/lib/tacticalInteractions.ts');
 const s=state(),original=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];
 s.crowdRegions=[{id:'south',name:'Crowd Region S',points:structuredClone(original),state:'idle',active:true}];
 assert.equal(ensureCrowdOriginals(s),true);assert.equal(ensureCrowdOriginals(s),false);
 saveCrowdSurgePreset(s,'south',{id:'a',name:'A',points:[{x:20,y:0},{x:30,y:0},{x:30,y:10},{x:20,y:10}]});
 saveCrowdSurgePreset(s,'south',{id:'b',name:'B',points:[{x:40,y:0},{x:50,y:0},{x:50,y:10},{x:40,y:10}]});
 triggerCrowdSurgePreset(s,'south','a');triggerCrowdSurgePreset(s,'south','b');
 assert.deepEqual(s.crowdRegions[0].originalPoints,original);returnCrowdToOriginal(s,'south');
 assert.deepEqual(s.crowdRegions[0].points,original);assert.equal(s.crowdRegions[0].state,'idle');
 s.crowdRegions[0].points=[{x:1,y:1},{x:2,y:1},{x:2,y:2}];setCrowdOriginal(s,'south');s.crowdRegions[0].points[0].x=99;assert.equal(s.crowdRegions[0].originalPoints?.[0].x,1);
});

test('crowd tether fields are backward compatible and prevent endpoint dragging',()=>{
 const s=state();s.crowdRegions=[{id:'south',name:'South',points:[{x:0,y:0},{x:10,y:0},{x:10,y:10}],state:'idle',active:true}];
 const tether=createTether({fromCrowdId:'south',toTokenId:'t'},'crowd-tether');assert.equal(tether.fromCrowdId,'south');assert.equal(tether.toTokenId,'t');
 s.tethers=[tether];moveTetherEndpoint(s,'crowd-tether','from',{x:99,y:99});assert.equal(s.tethers[0].from,undefined);
});

test('tether endpoint precedence uses live crowd polygon overrides',async()=>{
 const {tetherEndpoint}=await import('../src/lib/tacticalTethers.ts');const s=state();
 s.crowdRegions=[{id:'c',name:'Crowd',points:[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}],state:'idle',active:true}];
 assert.deepEqual(tetherEndpoint(s,{crowdId:'c',fallback:{x:99,y:99}}),{x:5,y:5});
 assert.deepEqual(tetherEndpoint(s,{crowdId:'c'},{c:[{x:20,y:0},{x:30,y:0},{x:30,y:10},{x:20,y:10}]}),{x:25,y:5});
 assert.deepEqual(tetherEndpoint(s,{tokenId:'t',crowdId:'c'}),{x:10,y:10});
});

test('anaglyph channels stay perpendicular and screen-space calibrated',async()=>{
 const {anaglyphChannelLines}=await import('../src/lib/tacticalTethers.ts');
 const atOne=anaglyphChannelLines({x:0,y:0},{x:100,y:0},6,1),atTwo=anaglyphChannelLines({x:0,y:0},{x:100,y:0},6,2);
 assert.deepEqual(atOne.red.a,{x:0,y:3});assert.deepEqual(atOne.cyan.a,{x:0,y:-3});
 assert.equal((atTwo.red.a.y-atTwo.cyan.a.y)*2,6);
 const vertical=anaglyphChannelLines({x:0,y:0},{x:0,y:100},6,1);assert.deepEqual(vertical.red.a,{x:-3,y:0});
});
test('new tethers default to normal and preserve anaglyph style',async()=>{const {createTether}=await import('../src/lib/tacticalInteractions.ts');assert.equal(createTether({from:{x:0,y:0},to:{x:1,y:1}}).style,'normal');assert.equal(createTether({from:{x:0,y:0},to:{x:1,y:1},style:'anaglyph'}).style,'anaglyph')});
