import type { TacticalState } from "../../types/tactical";
type Props={state:TacticalState;mode:"dm"|"presentation";zoom:number;pan:{x:number;y:number};svgRef?:React.Ref<SVGSVGElement>;selectedIds?:Set<string>;onTokenPointerDown?:(event:React.PointerEvent<SVGGElement>,id:string)=>void;onBackgroundPointerDown?:(event:React.PointerEvent<SVGSVGElement>)=>void;onPointerMove?:(event:React.PointerEvent<SVGSVGElement>)=>void;onPointerUp?:(event:React.PointerEvent<SVGSVGElement>)=>void};
const short=(name:string)=>name.replace(/[^a-z0-9]/gi,"").slice(0,3).toUpperCase();
export default function TacticalBattlefield({state,mode,zoom,pan,svgRef,selectedIds=new Set(),onTokenPointerDown,onBackgroundPointerDown,onPointerMove,onPointerUp}:Props){
 const g=state.battlefield,p=state.presentation,layers=p?.layers;const presentation=mode==="presentation";
 const tokens=state.tokens.filter(t=>presentation?(layers?.tokens!==false&&t.presentationVisible!==false&&t.visible&&(layers?.defeatedTokens!==false||!t.defeated)):t.visible);
 const zones=state.zones.filter(z=>presentation?(layers?.zones!==false&&z.presentationVisible!==false&&z.visible&&z.active):z.visible);
 const crowds=state.crowdRegions.filter(c=>presentation?(layers?.crowdRegions!==false&&c.presentationVisible!==false&&c.active):c.active);
 return <svg ref={svgRef} className={`battlefield battlefield-${mode}`} onPointerDown={onBackgroundPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} aria-label={presentation?"Player battlefield":"Tactical battlefield"}><defs><pattern id={`grid-${mode}`} width={g.gridSize} height={g.gridSize} patternUnits="userSpaceOnUse" x={g.gridOffsetX} y={g.gridOffsetY}><path d={`M ${g.gridSize} 0 L 0 0 0 ${g.gridSize}`} fill="none" stroke="rgba(211,199,235,.25)" strokeWidth="1"/></pattern>{tokens.map(t=><clipPath id={`token-${mode}-${t.id}`} key={t.id}><circle r={t.size/2-2}/></clipPath>)}</defs><g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}><rect width={g.width} height={g.height} className="battlefield-ground"/>{g.backgroundImageUrl&&(!presentation||layers?.background!==false)&&<image href={g.backgroundImageUrl} x={g.imageX} y={g.imageY} width={g.mapWidth?g.mapWidth*g.imageScale:g.width*g.imageScale} height={g.mapHeight?g.mapHeight*g.imageScale:undefined} preserveAspectRatio="xMidYMid meet"/>}{g.gridVisible&&(!presentation||layers?.grid!==false)&&<rect width={g.width} height={g.height} fill={`url(#grid-${mode})`}/>} {zones.map(z=><polygon key={z.id} points={z.points.map(q=>`${q.x},${q.y}`).join(" ")} className={`tactical-zone ${z.kind} ${z.active?"":"inactive"} ${mode==="dm"&&z.presentationVisible===false?"presentation-hidden":""}`}/>)}{crowds.map(c=><polygon key={c.id} points={c.points.map(q=>`${q.x},${q.y}`).join(" ")} className={`crowd-region ${c.state} ${mode==="dm"&&c.presentationVisible===false?"presentation-hidden":""}`}/>)}{tokens.map(t=><g key={t.id} className={`tactical-token ${t.category} ${selectedIds.has(t.id)?"selected":""} ${mode==="dm"&&t.presentationVisible===false?"presentation-hidden":""}`} transform={`translate(${t.x} ${t.y})`} onPointerDown={e=>onTokenPointerDown?.(e,t.id)}><circle r={t.size/2}/>{t.imageUrl&&<image href={t.imageUrl} x={-t.size/2} y={-t.size/2} width={t.size} height={t.size} preserveAspectRatio="xMidYMid slice" clipPath={`url(#token-${mode}-${t.id})`}/>} {(!presentation||layers?.tokenLabels!=="off")&&<text textAnchor="middle" y={t.size/2+18}>{presentation&&layers?.tokenLabels==="full"?t.name:(t.label||short(t.name))}</text>}{t.maxHp!=null&&(!presentation||layers?.hpBars)&&<rect x={-t.size/2} y={t.size/2+5} width={t.size*Math.max(0,(t.currentHp||0)/t.maxHp)} height="5" className="hp-bar"/>}{t.conditions.length>0&&(!presentation||layers?.conditions)&&<text className="condition-markers" textAnchor="middle" y={-t.size/2-7}>{t.conditions.slice(0,3).map(c=>c[0]).join(" · ")}</text>}</g>)}</g></svg>
}
